### ISSUE TITLE
Using customizable regexp in ``company-reftex-labels``

### ISSUE THREAD

**Issue by m-h-b-tu** [TheBB/company-reftex#1]
Just a minor request: Can ``company-reftex-labels`` use a customizable regexp for its _prefix_ command instead of the hardcoded string? This way it would be possible to support LaTeX packages like ``cleveref`` with their additional _ref_ commands (like ``\cref`` and ``\Cref``).

**Comment by TheBB** [comment]
Sure, added in https://github.com/TheBB/company-reftex/commit/cd16fd025c3f9c10cf0146eca514ec7f15d90056

Feel free to submit PRs though with more general regexps.
