### ISSUE TITLE
Customizable citation annotation

### ISSUE THREAD

**Issue by astoff** [TheBB/company-reftex#3]
It would be nice to make `company-reftex-annotate-labels` a string, which is then passed to `reftex-format-citation` to format the annotation (see also `company-reftex-citations-regexp`). The default would be `"%t"`.

Also, I think it would be no harm to let `company-reftex-citations-regexp` match anything of the form `\\[[:alpha:]]*cite`, so it catches `\textcite`, `\parencite`, etc.

**Comment by TheBB** [comment]
Thanks. I've opened #4. Look it over to see if it behaves the way you expect.

I'm a bit reluctant to make the regexps too generous, but I've now written them with the `rx` macro instead, which should make adding new cites easier. Added `textcite` and `parencite` while I was at it though.

**Comment by TheBB** [comment]
I'm not sure if there's a list of common citation macros anywhere.

**Comment by astoff** [comment]
Yes, it seems to work fine — thanks! As to common citation and cross-reference macros, there are the variables `reftex-cite-format-builtin` and `reftex-ref-style-alist`.

**Comment by TheBB** [comment]
Thanks!
