### ISSUE TITLE
`company-reftex-citations` opens bibliography file

### ISSUE THREAD

**Issue by agreselin** [TheBB/company-reftex#6]
On the first time it's used to complete a reference, `company-reftex-citations` makes Emacs open the bib file in the background without the user explicitly intending to do so.

To reproduce, open a tex file with a bibliograhy and complete a reference inside, e.g. `\cite{}`. In my case, C-x C-b at this point lists the bibliography file among open buffers.

**Comment by TheBB** [comment]
I don't think this package explicitly opens any file. It's probably reftex doing it in the background.

**Comment by agreselin** [comment]
I'm sorry, I just tried RefTeX's own completion mechanism and indeed it opens the bib file. I've hardly ever used RefTeX's completion and I had never noticed that.

Sorry for the pointless report, and thanks for your work on the package :-)

**Comment by TheBB** [comment]
No worries! Thanks for the vigilance. :-)
